title: Dynamicist's Digest
author: Tatsuya Akiba-Lewis
blog_title: Dynamicist's Digest
description: Easy-to-read, bite-sized summaries of astrophysics articles or concepts.
url: "https://astroakiba.com"
baseurl: ""
timezone: America/Los_Angeles
markdown: kramdown
permalink: /blog/:year/:month/:title/

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
